language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

  include:
    - name: formatting
      rust: stable
      before_install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

    - name: clippy
      rust: stable
      before_install:
        - rustup component add clippy
      script:
        - cargo clippy --all-features -- -D warnings

    - name: coverage
      rust: stable
      sudo: required
      dist: bionic
      addons:
        apt:
          packages:
            - libssl-dev
      before_script:
        - cargo install cargo-tarpaulin
      script:
        - cargo clean
        - cargo build
      after_success:
        - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    - name: WASM tests
      rust: stable
      addons:
        firefox: latest
        chrome: stable
      before_cache:
        - rm -rf /home/travis/.cargo/bin/wasm-pack
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - cd sigma-tree-wasm
        - wasm-pack build
        - wasm-pack test  --firefox --headless
        - wasm-pack test  --firefox --headless --release
        - wasm-pack test  --chrome  --headless
        - wasm-pack test  --chrome  --headless --release

    - name: JS tests
      sudo: true
      rust: stable
      before_cache:
        - rm -rf /home/travis/.cargo/bin/wasm-pack
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
        - curl -sSL "https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.xz" | tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.13.1-linux-x64/bin/node
        - curl https://www.npmjs.com/install.sh | bash
      script:
        - cd sigma-tree-wasm
        - wasm-pack build
        - npm install && npm run test

    - name: build for iOS
      os: osx
      osx_image: xcode11.3
      rust: stable
      before_install:
        - rustup target add aarch64-apple-ios x86_64-apple-ios
        - cargo install cargo-lipo
        - cargo install cbindgen
      script:
        - cargo lipo --release --targets=aarch64-apple-ios,x86_64-apple-ios

cache: cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo test --release --verbose --all
  - cargo doc --no-deps
