language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

  include:
    # Builds with wasm-pack.
    - name: WASM tests
      rust: stable
      addons:
        firefox: latest
        chrome: stable
      before_cache:
        - rm -rf /home/travis/.cargo/bin/wasm-pack
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - wasm-pack build
        - wasm-pack test  --firefox --headless
        - wasm-pack test  --firefox --headless --release
        - wasm-pack test  --chrome  --headless
        - wasm-pack test  --chrome  --headless --release

cache: cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo test --release --verbose --all
  - cargo doc --no-deps
