[workspace]
members = [
    "sigma-ser",
    "ergo-lib",
    "bindings/ergo-wallet-lib-wasm",
    "bindings/ergo-wallet-lib-c-core",
    "bindings/ergo-wallet-lib-c",
    "bindings/ergo-wallet-lib-android",
]
