[workspace]
members = [
    "sigma-ser",
    "sigma-tree",
    "bindings/ergo-wallet-lib-wasm",
    "bindings/ergo-wallet-lib-c-core",
    "bindings/ergo-wallet-lib-c",
    "bindings/ergo-wallet-lib-android",
    "sigma-testutil",
]
