[workspace]
members = [
    "sigma-ser",
    "ergo-lib",
    "bindings/ergo-lib-wasm",
    "bindings/ergo-lib-c-core",
    "bindings/ergo-lib-c",
    "bindings/ergo-lib-jni",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
