[package]
name = "ergotree-interpreter"
version = "0.5.1"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "ErgoTree interpreter"
repository = "https://github.com/ergoplatform/sigma-rust"
exclude = [
    "proptest-regressions/*"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sigma-ser = { version = "^0.2.0", path = "../sigma-ser" }
sigma-util = { version = "^0.2.0", path = "../sigma-util" }
ergotree-ir = { version = "^0.5.1", path = "../ergotree-ir" }
indexmap = "1.3.2"
k256 = { version = "0.4.2", features = ["rand", "zeroize"] }
blake2 = "0.9"
elliptic-curve = {version = "0.5.0", features = ["rand", "zeroize"]}
thiserror = "1"
num-bigint = "0.3.0"
rand = "0.7"
lazy_static = "1.4"
derive_more = "0.99"
impl-trait-for-tuples = "0.2.0"
num = "0.3.1"
proptest = {version = "1.0.0", optional = true }
proptest-derive = {version = "0.3.0", optional = true }
bs58 = "0.4.0"
base16 = "0.2.1"

[features]
default = []
arbitrary = ["proptest", "proptest-derive"]

[dev-dependencies]
ergotree-ir = { version = "^0.5.1", path = "../ergotree-ir", features = ["arbitrary"] }
ergoscript-compiler = { version = "^0.1.0", path = "../ergoscript-compiler" }
proptest = "1.0.0"
test-util = { version = "0.1.0", path = "../test-util" }

