[package]
name = "ergo-chain-types"
version = "0.1.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "Ergo blockchain types"
repository = "https://github.com/ergoplatform/sigma-rust"
exclude = [
    "proptest-regressions/*"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = "1"
derive_more = "0.99"
sigma-ser = { version = "^0.3.0", path = "../sigma-ser" }
sigma-util = { version = "^0.3.0", path = "../sigma-util" }
base16 = "0.2.1"
proptest-derive = {version = "0.3.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
url = "2.2"

[dependencies.serde_with]
version = "1.9.1"
features = [ "json" ]
optional = true

[dependencies.proptest]
# wasm support, via https://altsysrq.github.io/proptest-book/proptest/wasm.html
version = "1.0.0"
# The default feature set includes things like process forking which are not
# supported in Web Assembly.
default-features = false
# Enable using the `std` crate.
features = ["std"]
optional = true

[features]
default = ["json"]
arbitrary = ["proptest", "proptest-derive"]
json = ["serde", "serde_json", "serde_with"]

[dev-dependencies]
