[package]
name = "ergo-lib-c-core"
version = "0.5.1"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "Common code for ergo-lib C and JNI bindings"
repository = "https://github.com/ergoplatform/sigma-rust"

[lib]
crate-type = ["lib"]

[dependencies]
ergo-lib = { version = "^0.5.1", path = "../../ergo-lib" }
ergotree-ir = { version = "^0.5.1", path = "../../ergotree-ir" }
thiserror = "1"

