[package]
name = "ergo-lib-jni"
version = "0.23.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
repository.workspace = true
edition.workspace = true
description = "JNI bindings for ergo-lib"

[lib]
name = "ergowalletlibjni"
crate-type = ["staticlib", "cdylib"]
path = "src/main/rust/lib.rs"

[dependencies]
jni = "0.19.0"
log = "0.4.16"
ergo-lib = { workspace = true }
ergo-lib-c-core = { version = "^0.23.0", path = "../ergo-lib-c-core" }
