[package]
name = "ergo-lib-jni"
version = "0.15.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "JNI bindings for ergo-lib"
repository = "https://github.com/ergoplatform/sigma-rust"

[lib]
name = "ergowalletlibjni"
crate-type = ["staticlib", "cdylib"]
path = "src/main/rust/lib.rs"

[dependencies]
jni = "0.19.0"
log = "0.4.16"
ergo-lib = {version = "^0.16.0", path = "../../ergo-lib"}
ergo-lib-c-core = {version = "^0.16.0", path = "../ergo-lib-c-core"}
