[package]
name = "ergo-lib-c"
version = "0.1.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "C bindings for ergo-lib"
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
ffi_helpers = "0.2"
ergo-lib = { path = "../../ergo-lib"}
ergo-lib-c-core = { path = "../ergo-lib-c-core"}


[build-dependencies]
cbindgen = "0.14"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
