[package]
name = "ergo-lib-wasm"
version = "0.2.1"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "WASM bindings for ergo-lib"
repository = "https://github.com/ergoplatform/sigma-rust"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
js-sys = "0.3"

ergo-lib = { version = "0.2.0", path = "../../ergo-lib" }
# used in elliptic-curve(in ergo-lib), compiled here with WASM support
getrandom = {version = "0.1", features = ["wasm-bindgen"]}
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

[dependencies.wasm-bindgen]
version = "0.2"
features = ["serde-serialize"]

[dev-dependencies]
wasm-bindgen-test = "0.3.10"
proptest-derive = "0.2"

[dev-dependencies.proptest]
# wasm support, via https://altsysrq.github.io/proptest-book/proptest/wasm.html
version = "0.10"
# The default feature set includes things like process forking which are not
# supported in Web Assembly.
default-features = false
# Enable using the `std` crate.
features = ["std"]

[package.metadata.wasm-pack.profile.release]
# wasm-opt = ["-O", "--enable-mutable-globals"]
wasm-opt = false
