name: Android tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  android:
    name: run Android tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: |
          rustup target add armv7-linux-androideabi   # for arm
          rustup target add i686-linux-android        # for x86
          rustup target add aarch64-linux-android     # for arm64
          rustup target add x86_64-linux-android      # for x86_64

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          ndk: 21.3.6528147 
          script: cd ./bindings/ergo-lib-jni && ./gradlew connectedCheck

