name: Android tests
on: [push, pull_request]

jobs:
  android:
    name: run Android tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: |
          rustup target add armv7-linux-androideabi   # for arm
          rustup target add i686-linux-android        # for x86
          rustup target add aarch64-linux-android     # for arm64
          rustup target add x86_64-linux-android      # for x86_64

      - name: run tests
        working-directory: ./bindings/ergo-wallet-lib-android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

