name: cargo audit 

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: audit
          override: true
      - name: cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: -deny warnings
