name: Security audit 

on:
  push:
    branches:
      - master
      - develop
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    types:
      - opened
      - synchronize
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
