name: iOS build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: build (iOS)
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: install deps
        run: |
          rustup target add aarch64-apple-ios x86_64-apple-ios
          cargo install cargo-lipo
          cargo install cbindgen

      - name: build
        run: |
          cd bindings/ergo-lib-c
          cbindgen --config cbindgen.toml --crate ergo-lib-c --output h/ergo_wallet.h
          cd ../ergo-lib-ios
          cargo lipo --release --targets=aarch64-apple-ios,x86_64-apple-ios
          swift package generate-xcodeproj
          xcodebuild -project ./ErgoLib.xcodeproj -xcconfig ./Config/Release.xcconfig -sdk iphoneos
          xcodebuild -project ./ErgoLib.xcodeproj -xcconfig ./Config/Release.xcconfig -sdk iphonesimulator
