name: iOS build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: build (iOS)
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-11-10
          override: true

      - name: install deps
        run:
          cargo install cbindgen
      
      - name: generate C-bindings header file
        run: |
          cd bindings/ergo-lib-c
          cbindgen --config cbindgen.toml --crate ergo-lib-c --output h/ergo_wallet.h

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build and run tests
        run: |
          cargo build -p ergo-lib-c
          cd bindings/ergo-lib-ios
          swift test -Xlinker -L../../target/debug/
