name: WASM tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  wasm_tests:
    name: WASM tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/ergo-lib-wasm
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: install deps
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

      - name: run tests
        run: |
          wasm-pack build
          # wasm-pack test  --firefox --headless
          # wasm-pack test  --firefox --headless --release
          wasm-pack test  --chrome  --headless
          wasm-pack test  --chrome  --headless --release
